# Generated by Django 6.0.4 on 2026-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_lifespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('herb', 'Herb'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('flower', 'Flower'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('succulent', 'Succulent'), ('fern', 'Fern'), ('grass', 'Grass'), ('vine', 'Vine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('shade', 'Shade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, choices=[('dry', 'Dry / Drought-tolerant'), ('light', 'Light / Low water needs'), ('moderate', 'Moderate / regular watering'), ('moist', 'Moist / high water needs')], max_length=50),
        ),
    ]
